In [3]:
import numpy as np
import pandas as pd

In [ ]:
Practice

In [4]:
n_trials = nrows = 10_000
n_dice = ncols = 3

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[6, 3, 4],
       [4, 4, 2],
       [4, 4, 5],
       ...,
       [5, 5, 4],
       [5, 5, 6],
       [1, 1, 4]])

In [9]:
sums_by_trial = rolls.sum(axis=1)
sums_by_trial

array([13, 10, 13, ..., 14, 16,  6])

In [10]:
wins = sums_by_trial > 12
wins

array([ True, False,  True, ...,  True,  True, False])

In [11]:
win_rate = wins.astype(int).mean()
win_rate

0.2563

In [12]:
expected_winnings = win_rate * 15
cost = 5
expected_profit = expected_winnings - cost
expected_profit

-1.1555000000000004

In [17]:
## Exercises

In [34]:
## 1. How likely is it that you roll doubles when rolling two dice?
# Step 1: represent data
outcomes = [1,2,3,4,5,6]
#Step 2: create matrix
n_simulations = n_rows1 = 1_000_000
roll1 = np.random.choice(outcomes, n_simulations)
roll2 = np.random.choice(outcomes, n_simulations)


In [35]:
roll1

array([2, 3, 3, ..., 6, 3, 2])

In [36]:
roll2

array([3, 1, 5, ..., 6, 4, 6])

In [37]:
# Step 3: apply a row-wise aggregate
# compare die results to find when they are doubles
doubles = roll1 == roll2

In [38]:
doubles.mean()

0.166295

In [49]:
## 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the 
## probability of getting more than 3 heads?
# Step 1: represent the data
# 1 represents heads and 0 tails
outcomes2 = [1, 0]
# Step 2: create matrix
n_sims = 1_000_000
n_trials2 = 8
flips = np.random.choice(outcomes2, size=(n_sims, n_trials2))
flips

array([[0, 1, 1, ..., 1, 1, 1],
       [1, 1, 0, ..., 0, 1, 1],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 1, 1, ..., 0, 0, 1],
       [1, 0, 1, ..., 0, 1, 0],
       [1, 1, 0, ..., 0, 0, 0]])

In [52]:
num_of_heads = flips.sum(axis=1)

In [54]:
# what's the probability of rolling a 3?

(num_of_heads == 3).mean()

0.218242

In [55]:
(num_of_heads > 3).mean()

0.636983

In [56]:
num_of_heads

array([6, 5, 2, ..., 4, 4, 3])

In [58]:
num_of_heads == 3

array([False, False, False, ..., False, False,  True])

## 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup.
## Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds 
## that the two billboards I drive past both have data science students on them?


In [59]:
# 1 equals ds and 0 equal web dev
outcomes = [1,0]
sims3 = 10_000
trials3 = 2
students = np.random.choice(outcomes, size =(sims3, trials3), p=[.25,.75])
students

array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [0, 1],
       [1, 1],
       [1, 1]])

In [60]:
num_ds = students.sum(axis=1)

In [62]:
num_ds == 2

array([False, False, False, ..., False,  True,  True])

In [63]:
(num_ds == 2).mean()

0.0683

In [64]:
.25 * .25

0.0625

Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [69]:
np.random.normal(100, 20)
n_trials4 = 5
n_sims4 = 1_000_000
consumed = np.random.normal(3, 1.5,size = (n_sims4,n_trials4))

num_of_poptarts = consumed.sum(axis=1)

In [70]:
num_of_poptarts = consumed.sum(axis=1)

In [71]:
num_of_poptarts

array([12.73430043, 14.4765758 , 11.88088652, ..., 12.87529284,
       16.03876367, 18.29465218])

In [72]:
num_of_poptarts <= 16

array([ True,  True,  True, ...,  True, False, False])

In [74]:
(num_of_poptarts <= 16).mean()

0.617403

Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, P(woman taller than man)?

In [76]:
# man
n_trials5 = 1
n_sims5 = 1_000_000

men = np.random.normal(178, 8, size=(n_sims5, n_trials5))
men

array([[190.44625776],
       [185.57481111],
       [172.12921489],
       ...,
       [183.88924651],
       [151.59090595],
       [185.65524247]])

In [77]:
# woman
n_trials6 = 1
n_sims6 = 1_000_000

women = np.random.normal(170, 6, size=(n_sims6, n_trials6))
women

array([[175.69331959],
       [161.31116263],
       [173.64072859],
       ...,
       [166.27709758],
       [172.73505861],
       [170.06101653]])

In [78]:
(women > men).mean()

0.212088

6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 
students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 
students that download anaconda?

How likely is it that 450 students all download anaconda without an issue?

In [121]:
# 1 equals corrupt, 0 equals no issue
outcome7 = [1,0]
n_sims7 = 10_000
n_trials7 = 50

corrupt = np.random.choice(outcome7, size=(n_sims7,n_trials7), p=[.004,.996])
corrupt

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [122]:
1/250

0.004

In [123]:
n_times_corrupt =(corrupt.sum(axis=1))

In [125]:
1-(n_times_corrupt >= 1).mean()

0.8147

In [127]:
outcome7 = [1,0]
n_sims7 = 10_000
n_trials7 = 100

corrupt = np.random.choice(outcome7, size=(n_sims7,n_trials7), p=[.004,.996])
n_times_corrupt =(corrupt.sum(axis=1))
1-(n_times_corrupt >= 1).mean()

0.6694

In [129]:
outcome7 = [1,0]
n_sims7 = 10_000
n_trials7 = 150

corrupt = np.random.choice(outcome7, size=(n_sims7,n_trials7), p=[.004,.996])
n_times_corrupt =(corrupt.sum(axis=1))
1-(n_times_corrupt >= 1).mean()

0.55

In [130]:
outcome7 = [1,0]
n_sims7 = 10_000
n_trials7 = 450

corrupt = np.random.choice(outcome7, size=(n_sims7,n_trials7), p=[.004,.996])
n_times_corrupt =(corrupt.sum(axis=1))
1-(n_times_corrupt >= 1).mean()

0.16269999999999996